import pandas as pd

df : pd.DataFrame = pd.DataFrame()

data : list[dict[str, pd.Period | int]] = []
data.append({'year_month': pd.Timestamp(2023, 1, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2023, 2, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2023, 3, 1).to_period("M"),'quantity': 0})  
data.append({'year_month': pd.Timestamp(2023, 4, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2023, 5, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2023, 6, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2023, 7, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2023, 8, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2023, 9, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2023, 10, 1).to_period("M"),'quantity': 15})
data.append({'year_month': pd.Timestamp(2023, 11, 1).to_period("M"),'quantity': 210})
data.append({'year_month': pd.Timestamp(2023, 12, 1).to_period("M"),'quantity': 373})
data.append({'year_month': pd.Timestamp(2024, 1, 1).to_period("M"),'quantity': 136})
data.append({'year_month': pd.Timestamp(2024, 2, 1).to_period("M"),'quantity': 22})
data.append({'year_month': pd.Timestamp(2024, 3, 1).to_period("M"),'quantity': 3})
data.append({'year_month': pd.Timestamp(2024, 4, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2024, 5, 1).to_period("M"),'quantity': 2})
data.append({'year_month': pd.Timestamp(2024, 6, 1).to_period("M"),'quantity': 1})
data.append({'year_month': pd.Timestamp(2024, 7, 1).to_period("M"),'quantity': 1})
data.append({'year_month': pd.Timestamp(2024, 8, 1).to_period("M"),'quantity': 3})
data.append({'year_month': pd.Timestamp(2024, 9, 1).to_period("M"),'quantity': 2})
data.append({'year_month': pd.Timestamp(2024, 10, 1).to_period("M"),'quantity': 7})
data.append({'year_month': pd.Timestamp(2024, 11, 1).to_period("M"),'quantity': 17})
data.append({'year_month': pd.Timestamp(2024, 12, 1).to_period("M"),'quantity': 90})
data.append({'year_month': pd.Timestamp(2025, 1, 1).to_period("M"),'quantity': 61})
data.append({'year_month': pd.Timestamp(2025, 2, 1).to_period("M"),'quantity': 14})
data.append({'year_month': pd.Timestamp(2025, 3, 1).to_period("M"),'quantity': 3})
data.append({'year_month': pd.Timestamp(2025, 4, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2025, 5, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2025, 6, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2025, 7, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2025, 8, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2025, 9, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2025, 10, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2025, 11, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2025, 12, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2026, 1, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2026, 2, 1).to_period("M"),'quantity': 0})
data.append({'year_month': pd.Timestamp(2026, 3, 1).to_period("M"),'quantity': 0})

df = pd.DataFrame(data)

print(df)
