export const KO = {
  "sectionProductFilter": "상품 정보 · 필터",
  "warnSelfMarginPrefix": "자사 영업이익률",
  "warnSelfMarginMid": "이(가) 하한 ",
  "warnSelfMarginSuffix": " 미만입니다. 오더 확정을 사용할 수 없습니다.",
  "labelBrand": "브랜드",
  "labelCategory": "카테고리",
  "labelProductCode": "프로덕트 코드",
  "labelProductName": "상품명",
  "labelCompetitorChannel": "경쟁사 채널",
  "labelMinOpMargin": "영업이익률 하한 (%)",
  "sectionSales": "판매 정보",
  "thMetric": "지표",
  "thSelf": "자사",
  "rowAvgPrice": "평균 판매가",
  "rowQtyRank": "판매량 (순위)",
  "rowAmountRank": "판매액 (순위)",
  "rowAvgCost": "평균 원가 (원가 비율)",
  "rowGrossMarginUnit": "개당 매출이익",
  "rowFee": "평균 수수료 (수수료율)",
  "rowOpMargin": "영업이익 (이익률)",
  "sectionStock": "재고 및 오더",
  "labelDailyMean": "평균 일 판매량",
  "labelSigma": "일 판매량 표준편차",
  "labelServiceLevel": "서비스 수준",
  "labelLeadTime": "리드타임",
  "thSafetyStockCalc": "안전재고연산",
  "thForecastQtyCalc": "예측수량연산",
  "helpSafetyStockCalc": "Safety Stock = Z × σ × √L\nZ: 서비스수준 z값\nσ: 수요 표준편차(같은 단위)\nL: 리드타임(기간 수)",
  "helpForecastQtyCalc": "지정된 수식을 통해 연산되어 도출된 값입니다.",
  "helpServiceLevel": "목표 품절 위험을 반영하는 값입니다. 값이 높을수록 필요한 안전재고가 증가합니다. (예: 95%는 z≈1.65)",
  "helpLeadTime": "발주 후 입고까지 걸리는 일수입니다. 리드타임이 길수록 변동을 흡수할 안전재고가 커집니다.",
  "rowSafetyStock": "안전재고 (발주 제안)",
  "rowRecOrderQty": "추천 발주량 (합계)",
  "rowExpectedOrderAmt": "기대 오더액",
  "rowExpectedSales": "기대 판매금액",
  "rowExpectedOpProfit": "기대 영업이익",
  "sectionAi": "AI (목업)",
  "placeholderPrompt": "프롬프트를 입력하세요",
  "ariaLlmPrompt": "LLM 질의",
  "btnGenerating": "생성 중…",
  "btnAnswerGen": "답변 생성",
  "answerEmpty": "답변이 여기에 표시됩니다.",
  "sectionSizeOrder": "사이즈별 오더",
  "sectionSalesTrendDaily": "판매추이(일간)",
  "selfSizeMixBarTitle": "자사 사이즈 비율",
  "compSizeMixBarTitleSuffix": " 사이즈 비율",
  "selfWeight": "자사 가중치",
  "ariaWeightSlider": "자사 대 경쟁사 가중치",
  "competitorWeightApprox": "비중(어림값)",
  "thSize": "사이즈",
  "thSelfPct": "자사 비중 %",
  "thSharePctUnit": "비중 %",
  "thBlendedPct": "가중 비중 %",
  "thRecQty": "추천 수량",
  "thConfirmQty": "확정 수량",
  "btnApplyRec": "추천 수량 적용",
  "btnConfirmOrder": "오더 확정 (스냅샷 저장)",
  "hintSnapshot": "확정 시 이 패널 전체 상태와 LLM 질의·답변이 브라우저 localStorage에 저장됩니다.",
  "rankSuffix": "위"
} as const
