export const KO = {
  "labelBrand": "브랜드",
  "labelCategory": "카테고리",
  "labelProductCode": "상품 코드",
  "labelProductName": "상품명",
  "labelCompetitorChannel": "경쟁사 채널",
  "sectionSales": "판매 정보",
  "thMetric": "지표",
  "thSelf": "자사",
  "rowAvgPrice": "평균 판매가 (원)",
  "rowQtyRank": "판매량 (EA, 순위)",
  "rowAmountRank": "판매액 (원, 순위)",
  "rowAvgCost": "평균 원가 (원, 원가 비율 %)",
  "rowGrossMarginUnit": "개당 매출이익 (원)",
  "rowFee": "평균 수수료 (원, 수수료율 %)",
  "rowOpMargin": "영업이익 (원, 이익률 %)",
  "sectionSalesForecastIntegrated": "사이즈 통합 오더 설정",
  "labelCurrentOrderDate": "금번 오더 입고일",
  "labelNextOrderDate": "차기 오더 입고일",
  "labelBufferStock": "여유재고 설정",
  "labelUnitCost": "기대 원가",
  "labelUnitPrice": "기대 판매가",
  "labelExpectedFeeRate": "기대 수수료",
  "unitBufferStockDays": "일분",
  "unitWonPerEa": "원/EA",
  "labelDailyMeanSales": "일평균 판매량",
  "labelDailyMeanExpectedSales": "일평균 기대 판매량",
  "thSizeIntegratedColExpected": "예상",
  "thSizeIntegratedColConfirm": "확정",
  "helpForecastQtyCalc": "내부적으로 지정된 수식으로 도출된 예상 판매량을 기반으로 하여 일평균 기대 판매량을 도출합니다.",
  "rowOrderQty": "오더 수량 (EA)",
  "rowExpectedSales": "기대 매출 (원)",
  "rowExpectedOpProfit": "기대 영업이익 (원)",
  "rowExpectedOpProfitRate": "기대 영업이익율 (%)",
  "helpExpectedOpProfitRateLatex": "\\text{기대 영업이익율(\\%)}=\\frac{\\left(\\text{기대 매출}\\times(1-\\text{기대수수료율})\\right)-\\left(\\text{기대 원가}\\times\\text{기대 일평균 판매량}\\right)}{\\text{기대 매출}}\\times100",
  "rowCurrentStockQty": "현재 재고 수량(EA)",
  "rowTotalOrderBalance": "미입고 총 잔량(EA)",
  "helpTotalOrderBalance": "기 오더 되었으나,\n현 시점까지 입고되지 않은 수량입니다.",
  "rowExpectedInboundOrderBalance": "현오더 입고일전 미입고잔량(EA)",
  "helpExpectedInboundOrderBalance": "금번 오더 수량의 입고시까지의 오더 잔량입니다.",
  "sectionAi": "AI (목업)",
  "placeholderPrompt": "프롬프트를 입력하세요",
  "ariaLlmPrompt": "LLM 질의",
  "btnGenerating": "생성 중…",
  "btnAnswerGen": "답변 생성",
  "answerEmpty": "답변이 여기에 표시됩니다.",
  "sectionSizeOrder": "사이즈별 오더",
  "sectionSalesTrendDaily": "판매추이(일간)",
  "btnTrendSizeExpand": "펼치기",
  "btnTrendSizeDefault": "접기",
  "optionTrendDailySizeAll": "전체",
  "ariaTrendDailySizeSelect": "일간 판매추이 사이즈",
  "selfWeight": "자사 가중치",
  "ariaWeightSlider": "자사 대 경쟁사 가중치",
  "competitorWeightApprox": "가중치",
  "thSize": "사이즈",
  "thSharePctUnit": "사이즈 비중",
  "rowMetricAdjustReflectedSizeSharePct": "조정 반영 사이즈 비중(%)",
  "rowChartAdjustReflectedSharePct": "조정 반영",
  "rowShareMixLineChart": "비중",
  "rowSalesForecast": "판매 예측(EA)",
  "helpSalesForecastSizeOrder": "[사이즈 통합 오더 설정]의 일평균 기대 판매량(EA/일)에, 오늘부터 금번 오더 입고일까지 일수(양끝 포함)를 곱한 뒤,\n사이즈별 비율로 나눈 값을 소숫점 첫째자리에서 올림한 예측 수량(EA)입니다.",
  "thRecQty": "추천 수량(EA)",
  "helpSizeRecQty": "추천수량 = 판매예측수량 - 현재고수량 - 현오더입고일전미입고잔량 + 여유(안전)재고수량\n단, 여유재고수량 = 여유재고설정(일) × 일평균 기대 판매량(EA/일)",
  "thConfirmQty": "확정 수량(EA)",
  "thTotal": "합계",
  "btnConfirmOrder": "오더 담기",
  "btnSaveCandidateChanges": "변경 저장",
  "btnSelectCandidate": "후보군 선택",
  "btnDelete": "삭제",
  "btnCreateCandidateConfirm": "생성",
  "labelCandidateName": "후보군 이름",
  "labelCandidateNote": "비고",
  "msgNoNote": "비고 없음",
  "msgCandidateEmpty": "후보군이 없습니다.",
  "msgCandidateCreatedPopupSuffix": "가 생성되었습니다.",
  "hintSnapshot": "확정 시 이 패널 전체 상태와 LLM 질의·답변이 브라우저 localStorage에 저장됩니다.",
  "snapshotTestBadge": "테스트 전용",
  "snapshotTestTitle": "오더 스냅샷 JSON",
  "snapshotTestNote": "개발·확인용 미리보기입니다. 배포 전 제거하거나 플래그로 끄세요.",
  "btnSnapshotTestOk": "확인",
  "rankSuffix": "위"
} as const
