export const KO = {
  "sectionProductFilter": "상품 정보 · 필터",
  "warnSelfMarginPrefix": "자사 영업이익률",
  "warnSelfMarginMid": "이(가) 하한 ",
  "warnSelfMarginSuffix": " 미만입니다. 오더 확정을 사용할 수 없습니다.",
  "labelBrand": "브랜드",
  "labelCategory": "카테고리",
  "labelProductCode": "프로덕트 코드",
  "labelProductName": "상품명",
  "labelCompetitorChannel": "경쟁사 채널",
  "labelMinOpMargin": "영업이익률 하한 (%)",
  "sectionSales": "판매 정보",
  "thMetric": "지표",
  "thSelf": "자사",
  "rowAvgPrice": "평균 판매가",
  "rowQtyRank": "판매량 (순위)",
  "rowAmountRank": "판매액 (순위)",
  "rowAvgCost": "평균 원가 (원가 비율)",
  "rowGrossMarginUnit": "개당 매출이익",
  "rowFee": "평균 수수료 (수수료율)",
  "rowOpMargin": "영업이익 (이익률)",
  "sectionStock": "재고 및 오더",
  "labelDailyMean": "일평균 판매량(μ)",
  "labelSigma": "리드타임 시작일",
  "labelLeadTimeStartDate": "LT 시작",
  "labelLeadTimeEndDate": "LT 종료",
  "labelSafetyStockInput": "안전재고",
  "labelSafetyStockManual": "안전재고",
  "labelSafetyStockDerived": "안전재고 도출",
  "labelDirectInput": "안전재고 직접입력",
  "labelSafetyStockMode": "안전재고 기준",
  "optionSafetyStockManual": "직접 입력",
  "optionSafetyStockFormula": "계산식 사용 (Z × σ × √L)",
  "labelServiceLevel": "서비스 수준(p)",
  "labelLeadTime": "리드타임",
  "thSafetyStockCalc": "안전재고연산",
  "thForecastQtyCalc": "예측수량연산",
  "helpSafetyStockCalc": "Z: 서비스수준 z값\nσ: 판매량 표준편차(같은 단위)\nL: 리드타임(일)",
  "helpSafetyStockCalcFormulaLatex": "\\text{안전재고}=Z\\times\\sigma\\times\\sqrt{L}",
  "helpRecOrderQty": "발주량 제안 = 안전재고 + μ × L\nμ: 평균 일 판매량(같은 단위)\nL: 리드타임(일)",
  "helpForecastQtyCalc": "지정된 수식을 통해 연산되어 도출된 값입니다.",
  "helpServiceLevel": "목표 품절 위험을 반영하는 값입니다.\n값이 높을수록 필요한 안전재고가 증가합니다.\n(예: 95%는 z≈1.645)",
  "helpServiceLevelVars": "p: 서비스 수준(확률, 0~1)\nz: 표준정규 분위수",
  "helpServiceLevelInverseFormulaLatex": "z=\\Phi^{-1}(p)",
  "helpServiceLevelFormulaLatex": "\\Phi(z)=\\int_{-\\infty}^{z}\\frac{1}{\\sqrt{2\\pi}}e^{-t^2/2}\\,dt",
  "helpLeadTime": "리드타임 시작일~종료일의 캘린더 일수(양끝 포함)를 사용합니다. 기간이 길수록 변동과 기대 수요 반영량이 커집니다.",
  "rowSafetyStock": "안전 재고",
  "rowRecOrderQty": "발주량 제안",
  "rowExpectedOrderAmt": "기대 오더액",
  "rowExpectedSales": "기대 판매금액",
  "rowExpectedOpProfit": "기대 영업이익",
  "sectionAi": "AI (목업)",
  "placeholderPrompt": "프롬프트를 입력하세요",
  "ariaLlmPrompt": "LLM 질의",
  "btnGenerating": "생성 중…",
  "btnAnswerGen": "답변 생성",
  "answerEmpty": "답변이 여기에 표시됩니다.",
  "sectionSizeOrder": "사이즈별 오더",
  "sectionSalesTrendDaily": "판매추이(일간)",
  "btnTrendSizeExpand": "크게 보기",
  "btnTrendSizeDefault": "기본 크기",
  "selfWeight": "자사 가중치",
  "ariaWeightSlider": "자사 대 경쟁사 가중치",
  "competitorWeightApprox": "비중(어림값)",
  "thSize": "사이즈",
  "thSelfPct": "자사 비중 %",
  "thSharePctUnit": "비중 %",
  "rowShareMixLineChart": "비중 추이",
  "thBlendedPct": "가중 비중 %",
  "thRecQty": "추천 수량",
  "thConfirmQty": "확정 수량",
  "thTotal": "합계",
  "btnApplyRec": "추천 수량 적용",
  "btnConfirmOrder": "오더 확정 (스냅샷 저장)",
  "hintSnapshot": "확정 시 이 패널 전체 상태와 LLM 질의·답변이 브라우저 localStorage에 저장됩니다.",
  "rankSuffix": "위"
} as const
