export const KO: { readonly labelBrand: '브랜드'; readonly labelCategory: '카테고리'; readonly labelCode: '품번'; readonly labelColorCode: '색상'; readonly labelProductName: '상품명'; readonly labelCompetitorChannel: '경쟁사 채널'; readonly sectionSales: '판매 정보'; readonly salesMetricsTargetPeriod: '대상 기간'; readonly thMetric: '지표'; readonly thSelf: '자사'; readonly rowAvgPrice: '평균 판매가'; readonly rowQtyRank: '판매량'; readonly rowAmountRank: '판매액'; readonly rowAvgCost: '평균 원가'; readonly rowFee: '평균 수수료율'; readonly rowOpMargin: '평균 영업 이익율'; readonly sectionSalesForecastIntegrated: '통합 오더 설정'; readonly labelCurrentOrderInboundDueDate: '금번 오더 입고일'; readonly labelNextOrderInboundDueDate: '차기 오더 입고일'; readonly labelInboundSplitCount: '\uC785\uACE0\uBD84\uD560'; readonly unitInboundSplitCount: '\uD68C'; readonly btnInboundSplitSchedule: '\uBD84\uD560 \uC785\uACE0 \uC124\uC815'; readonly dialogInboundSplitTitle: '\uBD84\uD560 \uC785\uACE0 \uC124\uC815'; readonly thInboundSplitRound: '\uCC28\uC218'; readonly thInboundSplitInboundDate: '\uC785\uACE0\uC77C'; readonly thInboundSplitTotalQty: '\uC804\uCCB4 \uC218\uB7C9'; readonly rowInboundSplitSuggestedQty: '\uC81C\uC548'; readonly rowInboundSplitConfirmedQty: '\uD655\uC815'; readonly optionInboundSplitRoundSuffix: '\uCC28'; readonly ariaInboundSplitCount: '\uBD84\uD560 \uC785\uACE0 \uCC28\uC218'; readonly msgInboundSplitDraftOnly: '\uC801\uC6A9 \uC2DC \uD655\uC815 \uC218\uB7C9\uC5D0 \uBC18\uC601\uB429\uB2C8\uB2E4.'; readonly btnApplyInboundSplitSchedule: '\uC801\uC6A9'; readonly btnCloseInboundSplitDialog: '\uB2EB\uAE30'; readonly labelInboundSplitArrival: '\uC785\uACE0'; readonly labelInboundSplitDateInterval: '\uC785\uACE0\uC77C \uAC04\uACA9'; readonly unitDays: '\uC77C'; readonly ariaInboundSplitConfirmedDiff: '\uC81C\uC548 \uC218\uB7C9\uACFC \uB2E4\uB984'; readonly labelBufferStock: '여유재고 설정'; readonly labelUnitCost: '기대 원가'; readonly labelUnitPrice: '기대 판매가'; readonly labelExpectedFeeRate: '기대 수수료'; readonly unitBufferStockDays: '일분'; readonly unitWonPerEa: '원/EA'; readonly labelDailyMeanSales: '일평균 판매량'; readonly labelDailyMeanExpectedSales: '일평균 기대 판매량'; readonly thSizeIntegratedColExpected: '예상'; readonly thSizeIntegratedColConfirm: '확정'; readonly helpForecastQtyCalc: '오더 수량은 금번 오더 입고일부터 차기 오더 입고일까지의 예상 수요를 기준으로 산출합니다.\n일평균 기대 판매량은 선택 시작월부터 차기 오더 입고월까지의 예측 판매량 평균을 사용하며, 사이즈별 확정 수량 합계가 이 행에 표시됩니다.'; readonly rowOrderQty: '오더 수량 (EA)'; readonly rowExpectedSales: '기대 매출 (원)'; readonly rowExpectedOpProfit: '기대 영업이익 (원, %)'; readonly rowExpectedOpProfitRate: '기대 영업이익률 (%)'; readonly helpExpectedOpProfitRateLatex: '\\text{기대 영업이익률(\\%)}=\\frac{\\left(\\text{기대 매출}\\times\\left(1-\\frac{\\text{기대 수수료율}}{100}\\right)\\right)-\\left(\\text{기대 원가}\\times\\text{주문 수량}\\right)}{\\text{기대 매출}}\\times100'; readonly valueNotCalculated: '미계산'; readonly msgStockOrderCalcRequired: '재고/발주 계산이 완료된 뒤 저장 또는 AI 요청을 진행할 수 있습니다.'; readonly msgSalesInsightRequired: '판매 정보가 조회된 뒤 저장 또는 AI 요청을 진행할 수 있습니다.'; readonly rowCurrentStockQty: '현재 재고 수량(EA)'; readonly rowTotalOrderBalance: '미입고 총 잔량(EA)'; readonly helpTotalOrderBalance: '기 오더 되었으나,\n현 시점까지 입고되지 않은 수량입니다.'; readonly rowExpectedInboundOrderBalance: '현오더 입고전 미입고잔량(EA)'; readonly helpExpectedInboundOrderBalance: '금번 오더 수량의 입고시까지의 오더 잔량입니다.'; readonly sectionAi: 'AI 코멘트'; readonly aiCommentErrorPrefix: 'AI 코멘트 요청 실패'; readonly answerEmpty: 'AI 코멘트가 여기에 표시됩니다.'; readonly btnAiCommentExpand: '한번에 보기'; readonly btnAiCommentCollapse: '접기'; readonly sectionSizeOrder: '오더 상세'; readonly sectionSalesTrendDaily: '판매추이(일간)'; readonly btnTrendSizeExpand: '펼치기'; readonly btnTrendSizeDefault: '접기'; readonly optionTrendDailySizeAll: '전체'; readonly ariaTrendDailySizeSelect: '일간 판매추이 사이즈'; readonly selfWeight: '자사 가중치'; readonly ariaWeightSlider: '자사 대 비교 대상 가중치'; readonly comparisonWeightApprox: '가중치'; readonly thSize: '사이즈'; readonly thSharePctUnit: '사이즈 비중'; readonly rowMetricAdjustReflectedSizeSharePct: '조정 반영 사이즈 비중(%)'; readonly rowChartAdjustReflectedSharePct: '조정 반영'; readonly rowShareMixLineChart: '비중'; readonly rowSalesForecast: '판매 예측(EA)'; readonly helpSalesForecastSizeOrder: '[통합 오더 설정]의 일평균 기대 판매량(EA/일)에, 금번 오더 입고일부터 차기 오더 입고일까지 일수(양끝 포함)를 곱한 뒤,\n사이즈별 비율로 나눈 값을 소숫점 첫째자리에서 올림한 예측 수량(EA)입니다.'; readonly thRecQty: '추천 수량(EA)'; readonly helpSizeRecQty: '추천수량 = 판매예측수량 - 현재고수량 - 현오더입고일전미입고잔량 + 여유(안전)재고수량\n단, 여유재고수량 = 여유재고설정(일) × 일평균 기대 판매량(EA/일)'; readonly thConfirmQty: '확정 수량(EA)'; readonly thTotal: '합계'; readonly btnConfirmOrder: '오더 담기'; readonly btnConfirmCandidateDetail: '확정 저장'; readonly btnUnconfirmCandidateDetail: '확정 해제'; readonly btnResetCandidateDraft: '초기화'; readonly btnRestoreConfirmedCandidateDraft: '확정값 보기'; readonly btnSelectCandidate: '후보군 선택'; readonly btnDelete: '삭제'; readonly btnCreateCandidateConfirm: '생성'; readonly btnRequestAiComment: '코멘트 요청'; readonly labelCandidateName: '후보군 이름'; readonly labelCandidateNote: '비고'; readonly msgNoNote: '비고 없음'; readonly msgCandidateEmpty: '후보군이 없습니다.'; readonly hintSnapshot: '확정 시 2차 드로워 상태와 AI 코멘트가 선택한 후보군 이너 오더에 저장됩니다.'; readonly rankSuffix: '위'; } = {
  "labelBrand": "브랜드",
  "labelCategory": "카테고리",
  "labelCode": "품번",
  "labelColorCode": "색상",
  "labelProductName": "상품명",
  "labelCompetitorChannel": "경쟁사 채널",
  "sectionSales": "판매 정보",
  "salesMetricsTargetPeriod": "대상 기간",
  "thMetric": "지표",
  "thSelf": "자사",
  "rowAvgPrice": "평균 판매가",
  "rowQtyRank": "판매량",
  "rowAmountRank": "판매액",
  "rowAvgCost": "평균 원가",
  "rowFee": "평균 수수료율",
  "rowOpMargin": "평균 영업 이익율",
  "sectionSalesForecastIntegrated": "통합 오더 설정",
  "labelCurrentOrderInboundDueDate": "금번 오더 입고일",
  "labelNextOrderInboundDueDate": "차기 오더 입고일",
  "labelInboundSplitCount": "\uC785\uACE0\uBD84\uD560",
  "unitInboundSplitCount": "\uD68C",
  "btnInboundSplitSchedule": "\uBD84\uD560 \uC785\uACE0 \uC124\uC815",
  "dialogInboundSplitTitle": "\uBD84\uD560 \uC785\uACE0 \uC124\uC815",
  "thInboundSplitRound": "\uCC28\uC218",
  "thInboundSplitInboundDate": "\uC785\uACE0\uC77C",
  "thInboundSplitTotalQty": "\uC804\uCCB4 \uC218\uB7C9",
  "rowInboundSplitSuggestedQty": "\uC81C\uC548",
  "rowInboundSplitConfirmedQty": "\uD655\uC815",
  "optionInboundSplitRoundSuffix": "\uCC28",
  "ariaInboundSplitCount": "\uBD84\uD560 \uC785\uACE0 \uCC28\uC218",
  "msgInboundSplitDraftOnly": "\uC801\uC6A9 \uC2DC \uD655\uC815 \uC218\uB7C9\uC5D0 \uBC18\uC601\uB429\uB2C8\uB2E4.",
  "btnApplyInboundSplitSchedule": "\uC801\uC6A9",
  "btnCloseInboundSplitDialog": "\uB2EB\uAE30",
  "labelInboundSplitArrival": "\uC785\uACE0",
  "labelInboundSplitDateInterval": "\uC785\uACE0\uC77C \uAC04\uACA9",
  "unitDays": "\uC77C",
  "ariaInboundSplitConfirmedDiff": "\uC81C\uC548 \uC218\uB7C9\uACFC \uB2E4\uB984",
  "labelBufferStock": "여유재고 설정",
  "labelUnitCost": "기대 원가",
  "labelUnitPrice": "기대 판매가",
  "labelExpectedFeeRate": "기대 수수료",
  "unitBufferStockDays": "일분",
  "unitWonPerEa": "원/EA",
  "labelDailyMeanSales": "일평균 판매량",
  "labelDailyMeanExpectedSales": "일평균 기대 판매량",
  "thSizeIntegratedColExpected": "예상",
  "thSizeIntegratedColConfirm": "확정",
  "helpForecastQtyCalc": "오더 수량은 금번 오더 입고일부터 차기 오더 입고일까지의 예상 수요를 기준으로 산출합니다.\n일평균 기대 판매량은 선택 시작월부터 차기 오더 입고월까지의 예측 판매량 평균을 사용하며, 사이즈별 확정 수량 합계가 이 행에 표시됩니다.",
  "rowOrderQty": "오더 수량 (EA)",
  "rowExpectedSales": "기대 매출 (원)",
  "rowExpectedOpProfit": "기대 영업이익 (원, %)",
  "rowExpectedOpProfitRate": "기대 영업이익률 (%)",
  "helpExpectedOpProfitRateLatex": "\\text{기대 영업이익률(\\%)}=\\frac{\\left(\\text{기대 매출}\\times\\left(1-\\frac{\\text{기대 수수료율}}{100}\\right)\\right)-\\left(\\text{기대 원가}\\times\\text{주문 수량}\\right)}{\\text{기대 매출}}\\times100",
  "valueNotCalculated": "미계산",
  "msgStockOrderCalcRequired": "재고/발주 계산이 완료된 뒤 저장 또는 AI 요청을 진행할 수 있습니다.",
  "msgSalesInsightRequired": "판매 정보가 조회된 뒤 저장 또는 AI 요청을 진행할 수 있습니다.",
  "rowCurrentStockQty": "현재 재고 수량(EA)",
  "rowTotalOrderBalance": "미입고 총 잔량(EA)",
  "helpTotalOrderBalance": "기 오더 되었으나,\n현 시점까지 입고되지 않은 수량입니다.",
  "rowExpectedInboundOrderBalance": "현오더 입고전 미입고잔량(EA)",
  "helpExpectedInboundOrderBalance": "금번 오더 수량의 입고시까지의 오더 잔량입니다.",
  "sectionAi": "AI 코멘트",
  "aiCommentErrorPrefix": "AI 코멘트 요청 실패",
  "answerEmpty": "AI 코멘트가 여기에 표시됩니다.",
  "btnAiCommentExpand": "한번에 보기",
  "btnAiCommentCollapse": "접기",
  "sectionSizeOrder": "오더 상세",
  "sectionSalesTrendDaily": "판매추이(일간)",
  "btnTrendSizeExpand": "펼치기",
  "btnTrendSizeDefault": "접기",
  "optionTrendDailySizeAll": "전체",
  "ariaTrendDailySizeSelect": "일간 판매추이 사이즈",
  "selfWeight": "자사 가중치",
  "ariaWeightSlider": "자사 대 비교 대상 가중치",
  "comparisonWeightApprox": "가중치",
  "thSize": "사이즈",
  "thSharePctUnit": "사이즈 비중",
  "rowMetricAdjustReflectedSizeSharePct": "조정 반영 사이즈 비중(%)",
  "rowChartAdjustReflectedSharePct": "조정 반영",
  "rowShareMixLineChart": "비중",
  "rowSalesForecast": "판매 예측(EA)",
  "helpSalesForecastSizeOrder": "[통합 오더 설정]의 일평균 기대 판매량(EA/일)에, 금번 오더 입고일부터 차기 오더 입고일까지 일수(양끝 포함)를 곱한 뒤,\n사이즈별 비율로 나눈 값을 소숫점 첫째자리에서 올림한 예측 수량(EA)입니다.",
  "thRecQty": "추천 수량(EA)",
  "helpSizeRecQty": "추천수량 = 판매예측수량 - 현재고수량 - 현오더입고일전미입고잔량 + 여유(안전)재고수량\n단, 여유재고수량 = 여유재고설정(일) × 일평균 기대 판매량(EA/일)",
  "thConfirmQty": "확정 수량(EA)",
  "thTotal": "합계",
  "btnConfirmOrder": "오더 담기",
  "btnConfirmCandidateDetail": "확정 저장",
  "btnUnconfirmCandidateDetail": "확정 해제",
  "btnResetCandidateDraft": "초기화",
  "btnRestoreConfirmedCandidateDraft": "확정값 보기",
  "btnSelectCandidate": "후보군 선택",
  "btnDelete": "삭제",
  "btnCreateCandidateConfirm": "생성",
  "btnRequestAiComment": "코멘트 요청",
  "labelCandidateName": "후보군 이름",
  "labelCandidateNote": "비고",
  "msgNoNote": "비고 없음",
  "msgCandidateEmpty": "후보군이 없습니다.",
  "hintSnapshot": "확정 시 2차 드로워 상태와 AI 코멘트가 선택한 후보군 이너 오더에 저장됩니다.",
  "rankSuffix": "위"
} as const
