export const KO = {
  "labelBrand": "브랜드",
  "labelCategory": "카테고리",
  "labelCode": "품번",
  "labelColorCode": "색상",
  "labelProductName": "상품명",
  "labelCompetitorChannel": "경쟁사 채널",
  "sectionSales": "판매 정보",
  "salesMetricsTargetPeriod": "대상 기간",
  "thMetric": "지표",
  "thSelf": "자사",
  "rowAvgPrice": "평균 판매가",
  "rowQtyRank": "판매량",
  "rowAmountRank": "판매액",
  "rowAvgCost": "평균 원가",
  "rowFee": "평균 수수료율",
  "rowOpMargin": "평균 영업 이익율",
  "sectionSalesForecastIntegrated": "통합 오더 설정",
  "labelCurrentOrderInboundDueDate": "금번 오더 입고일",
  "labelNextOrderInboundDueDate": "차기 오더 입고일",
  "labelInboundSplitCount": "\uC785\uACE0\uBD84\uD560",
  "unitInboundSplitCount": "\uD68C",
  "btnInboundSplitSchedule": "\uBD84\uD560 \uC785\uACE0 \uC124\uC815",
  "btnInboundSplitLockDates": "\uC785\uACE0\uC77C \uD655\uC815",
  "btnInboundSplitUnlockDates": "\uC785\uACE0\uC77C \uD655\uC815 \uD574\uC81C",
  "btnInboundSplitResetConfirmed": "\uD655\uC815\uAC12 \uCD08\uAE30\uD654",
  "dialogInboundSplitTitle": "\uBD84\uD560 \uC785\uACE0 \uC124\uC815",
  "helpInboundSplitSchedule": "각 차수의 제안 수량은 먼저 전체 목표 수량을 고정한 뒤, 해당 입고일부터 다음 차수 입고일 전일까지의 일별 판매예측 비중으로 나눕니다.\n차수 총량은 사이즈별 판매 비중으로 배분합니다.\n기오더 입고 전 미입고량 제외를 선택하면 전체 목표 수량 산정에서 현오더 입고전 미입고잔량만 제외하고 현재 재고는 반영합니다.\n분할 적용 시 각 사이즈의 전체 확정 수량은 오더 상세의 추천 수량 합계와 다소 달라질 수 있습니다.",
  "btnInboundSplitDebugCopySource": "테스트 데이터 복사",
  "msgInboundSplitDebugSourceCopied": "복사됨",
  "msgInboundSplitDebugSourceCopyFailed": "복사 실패",
  "labelAll": "\uC804\uCCB4",
  "thInboundSplitRound": "\uCC28\uC218",
  "thInboundSplitInboundDate": "\uC785\uACE0\uC77C",
  "thInboundSplitTotalQty": "\uC218\uB7C9 \uD569",
  "labelInboundSplitSuggestionBasis": "\uC81C\uC548 \uADFC\uAC70",
  "labelInboundSplitBasisSalesForecast": "\uCC28\uC218\uAC04 \uC608\uC0C1 \uD310\uB9E4\uB7C9",
  "labelInboundSplitBasisExpectedInbound": "\uCC28\uC218\uAC04 \uC785\uACE0\uB7C9",
  "labelInboundSplitBasisCarriedStock": "\uC774\uC804\uCC28\uC218 \uC7AC\uACE0\uC774\uC804",
  "labelInboundSplitBasisTargetEndingStock": "\uBAA9\uD45C \uC794\uC5EC\uC7AC\uACE0",
  "rowInboundSplitSuggestedQty": "\uC81C\uC548",
  "rowInboundSplitConfirmedQty": "\uD655\uC815",
  "optionInboundSplitRoundSuffix": "\uCC28",
  "ariaInboundSplitCount": "\uBD84\uD560 \uC785\uACE0 \uCC28\uC218",
  "msgInboundSplitDraftOnly": "\uC785\uACE0 \uBD84\uD560 \uBCC0\uACBD \uC2DC, \uAC01 \uC0AC\uC774\uC988\uC758 \uC804\uCCB4 \uD655\uC815 \uC218\uB7C9\uC5D0 \uBCC0\uB3D9\uC774 \uC0DD\uAE38 \uC218 \uC788\uC2B5\uB2C8\uB2E4.",
  "btnApplyInboundSplitSchedule": "\uC801\uC6A9",
  "btnCloseInboundSplitDialog": "\uB2EB\uAE30",
  "labelInboundSplitArrival": "\uC785\uACE0",
  "labelInboundSplitDateInterval": "\uC785\uACE0\uC77C \uAC04\uACA9",
  "labelInboundSplitIgnoreExistingOrderInbound": "\uAE30 \uC624\uB354 \uC785\uACE0 \uC804 \uBBF8\uC785\uACE0\uB7C9 \uC81C\uC678",
  "msgInboundSplitInvalidDatePolicy": "\uC785\uACE0\uC77C \uAC04\uACA9\uC774 \uC62C\uBC14\uB974\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4. \uAC01 \uCC28\uC218 \uC785\uACE0\uC77C\uC740 \uAE08\uBC88 \uC624\uB354 \uC785\uACE0\uC77C \uC774\uC0C1, \uCC28\uAE30 \uC624\uB354 \uC785\uACE0\uC77C \uBBF8\uB9CC\uC774\uC5B4\uC57C \uD558\uBA70 \uC774\uC804 \uCC28\uC218\uBCF4\uB2E4 \uBE68\uB77C\uC9C8 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.",
  "valueNotApplicable": "\uD574\uB2F9 \uC5C6\uC74C",
  "labelPreviousDay": "\uC804\uC77C",
  "unitDays": "\uC77C",
  "unitEa": "EA",
  "ariaInboundSplitConfirmedDiff": "\uC81C\uC548 \uC218\uB7C9\uACFC \uB2E4\uB984",
  "labelBufferStock": "여유재고 설정",
  "labelUnitCost": "기대 원가",
  "labelUnitPrice": "기대 판매가",
  "labelExpectedFeeRate": "기대 수수료",
  "unitBufferStockDays": "일분",
  "unitWonPerEa": "원/EA",
  "labelDailyMeanSales": "일평균 판매량",
  "labelDailyMeanExpectedSales": "일평균 기대 판매량",
  "thSizeIntegratedColExpected": "예상",
  "thSizeIntegratedColConfirm": "확정",
  "helpForecastQtyCalc": "오더 수량은 금번 오더 입고일부터 차기 오더 입고일까지의 예상 수요를 기준으로 산출합니다.\n일평균 기대 판매량은 선택 시작월부터 차기 오더 입고월까지의 예측 판매량 평균을 사용하며, 사이즈별 확정 수량 합계가 이 행에 표시됩니다.",
  "rowOrderQty": "오더 수량 (EA)",
  "rowExpectedSales": "기대 매출 (원)",
  "rowExpectedOpProfit": "기대 영업이익 (원, %)",
  "rowExpectedOpProfitRate": "기대 영업이익률 (%)",
  "helpExpectedOpProfitRateLatex": "\\text{기대 영업이익률(\\%)}=\\frac{\\left(\\text{기대 매출}\\times\\left(1-\\frac{\\text{기대 수수료율}}{100}\\right)\\right)-\\left(\\text{기대 원가}\\times\\text{주문 수량}\\right)}{\\text{기대 매출}}\\times100",
  "valueNotCalculated": "미계산",
  "msgStockOrderCalcRequired": "재고/발주 계산이 완료된 뒤 저장 또는 AI 요청을 진행할 수 있습니다.",
  "msgSalesInsightRequired": "판매 정보가 조회된 뒤 저장 또는 AI 요청을 진행할 수 있습니다.",
  "rowCurrentStockQty": "현재 재고 수량(EA)",
  "rowTotalOrderBalance": "미입고 총 잔량(EA)",
  "helpTotalOrderBalance": "기 오더 되었으나,\n현 시점까지 입고되지 않은 수량입니다.",
  "rowExpectedInboundOrderBalance": "현오더 입고전 미입고잔량(EA)",
  "rowLastInboundExpectedInboundOrderBalance": "마지막 입고전 미입고 잔량(EA)",
  "helpExpectedInboundOrderBalance": "입고분할 1회는 금번 오더 입고 전까지의 기오더 미입고잔량입니다. 2회 이상은 마지막 차수 입고 전까지의 기오더 미입고잔량입니다.",
  "sectionAi": "AI 코멘트",
  "aiCommentErrorPrefix": "AI 코멘트 요청 실패",
  "answerEmpty": "AI 코멘트가 여기에 표시됩니다.",
  "btnAiCommentExpand": "한번에 보기",
  "btnAiCommentCollapse": "접기",
  "sectionSizeOrder": "오더 상세",
  "sectionSalesTrendDaily": "판매추이(일간)",
  "btnTrendSizeExpand": "펼치기",
  "btnTrendSizeDefault": "접기",
  "optionTrendDailySizeAll": "전체",
  "ariaTrendDailySizeSelect": "일간 판매추이 사이즈",
  "selfWeight": "자사 가중치",
  "ariaWeightSlider": "자사 대 비교 대상 가중치",
  "comparisonWeightApprox": "가중치",
  "thSize": "사이즈",
  "thSharePctUnit": "사이즈 비중",
  "rowMetricAdjustReflectedSizeSharePct": "조정 반영 사이즈 비중(%)",
  "rowChartAdjustReflectedSharePct": "조정 반영",
  "rowShareMixLineChart": "비중",
  "rowSalesForecast": "판매 예측(EA)",
  "helpSalesForecastSizeOrder": "[통합 오더 설정]의 일평균 기대 판매량(EA/일)에, 금번 오더 입고일부터 차기 오더 입고일까지 일수(양끝 포함)를 곱한 뒤,\n사이즈별 비율로 나눈 값을 소숫점 첫째자리에서 올림한 예측 수량(EA)입니다.",
  "thRecQty": "추천 수량(EA)",
  "helpSizeRecQty": "추천수량 = 판매예측수량 - 현재고수량 - 현오더입고일전미입고잔량 + 여유(안전)재고수량\n단, 여유재고수량 = 여유재고설정(일) × 일평균 기대 판매량(EA/일)",
  "thConfirmQty": "확정 수량(EA)",
  "thTotal": "합계",
  "btnConfirmOrder": "오더 담기",
  "btnConfirmCandidateDetail": "확정 저장",
  "btnUnconfirmCandidateDetail": "확정 해제",
  "btnResetCandidateDraft": "초기화",
  "btnRestoreConfirmedCandidateDraft": "확정값 보기",
  "btnSelectCandidate": "후보군 선택",
  "btnDelete": "삭제",
  "btnCreateCandidateConfirm": "생성",
  "btnRequestAiComment": "코멘트 요청",
  "labelCandidateName": "후보군 이름",
  "labelCandidateNote": "비고",
  "msgNoNote": "비고 없음",
  "msgCandidateEmpty": "후보군이 없습니다.",
  "hintSnapshot": "확정 시 2차 드로워 상태와 AI 코멘트가 선택한 후보군 이너 오더에 저장됩니다.",
  "rankSuffix": "위"
} as const
