import type { OrderSnapshotDocumentV2 } from '../api/types'
import { describe, expect, it } from 'vitest'
import { parseOrderSnapshot } from './parseOrderSnapshot'
import { validSnapshot } from './orderSnapshotTestFixtures'

describe('parseOrderSnapshot', () : void => {
  it('returns current snapshot when required fields are valid', () : void => {
    const parsed: OrderSnapshotDocumentV2 = parseOrderSnapshot(validSnapshot)
    expect(parsed).toEqual(validSnapshot)
    expect(parsed).not.toBe(validSnapshot)
  })

  it('preserves top-level companyUuid when it is a valid non-empty string', () : void => {
    const withCompanyUuid: { companyUuid: string; schemaVersion: 2; skuGroupKey: 'B'; savedAt: '2026-04-23T00:00:00.000Z'; context: { readonly periodStart: '2026-01-01'; readonly periodEnd: '2026-01-31'; readonly forecastMonths: 8; readonly dailyTrendStartMonth: '2026-01'; readonly dailyTrendLeadTimeDays: 30; }; drawer1: { readonly summary: { readonly skuGroupKey: 'B'; readonly productName: 'Runner'; readonly brand: 'Brand'; readonly category: 'Shoes'; readonly code: 'RUN'; readonly colorCode: 'BLK'; readonly price: 100000; readonly qty: 80; readonly availableStock: 20; }; }; drawer2: { readonly competitorBasis: { readonly skuGroupKey: 'B'; readonly competitorPrice: 120000; readonly competitorQty: 32; readonly competitorRatioBySize: { readonly '250': 0.6; }; }; readonly competitorChannelId: 'cream'; readonly competitorChannelLabel: 'Cream'; readonly bufferStock: 0; readonly selfWeightPct: 50; readonly aiComment: { readonly prompt: 'prompt'; readonly answer: 'comment'; readonly generatedAt: '2026-04-23T00:00:00.000Z'; }; readonly stockOrderRequest: { readonly currentOrderInboundDueDate: '2026-02-01'; readonly nextOrderInboundDueDate: '2026-02-28'; readonly leadTimeDays: 30; readonly dailyMeanOverride: 10; }; readonly stockOrderResult: { readonly trendDailyMean: 10; readonly dailyMean: 10; readonly sigma: 1; readonly display: { readonly currentStockQtyTotal: 20; readonly totalOrderBalanceTotal: 4; readonly expectedInboundOrderBalanceTotal: 2; readonly sizeRows: readonly [{ readonly size: '250'; readonly currentStockQty: 20; readonly totalOrderBalance: 4; readonly expectedInboundOrderBalance: 2; }]; }; readonly safetyStockCalc: { readonly safetyStock: 12; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; readonly forecastQtyCalc: { readonly safetyStock: null; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; }; readonly unitEconomics: { readonly unitPrice: 100000; readonly unitCost: 60000; readonly expectedFeeRatePct: 12; }; readonly confirmedTotals: { readonly orderQty: 12; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; readonly expectedOpProfitRatePct: 28; }; readonly sizeOrders: readonly [{ readonly size: '250'; readonly selfSharePct: 40; readonly competitorSharePct: 60; readonly blendedSharePct: 50; readonly forecastQty: 10; readonly recommendedQty: 12; readonly confirmQty: 12; }]; }; } = {
      ...validSnapshot,
      companyUuid: 'company-uuid-001',
    }

    const parsed: OrderSnapshotDocumentV2 = parseOrderSnapshot(withCompanyUuid)

    expect(parsed.companyUuid).toBe('company-uuid-001')
    expect(parsed).toEqual(withCompanyUuid)
  })

  it('does not add top-level companyUuid when it is omitted', () : void => {
    const parsed: OrderSnapshotDocumentV2 = parseOrderSnapshot(validSnapshot)

    expect(parsed).not.toHaveProperty('companyUuid')
  })

  it('strips fields that are not part of the current v2 snapshot contract', () : void => {
    const withExtra: { extraMeta: { source: string; }; context: { unknownContextField: boolean; periodStart: '2026-01-01'; periodEnd: '2026-01-31'; forecastMonths: 8; dailyTrendStartMonth: '2026-01'; dailyTrendLeadTimeDays: 30; }; drawer1: { unknownDrawer1Field: boolean; summary: { unknownSummaryField: boolean; skuGroupKey: 'B'; productName: 'Runner'; brand: 'Brand'; category: 'Shoes'; code: 'RUN'; colorCode: 'BLK'; price: 100000; qty: 80; availableStock: 20; }; }; drawer2: { unknownDrawer2Field: boolean; stockOrderRequest: { unknownStockOrderRequestField: boolean; currentOrderInboundDueDate: '2026-02-01'; nextOrderInboundDueDate: '2026-02-28'; leadTimeDays: 30; dailyMeanOverride: 10; }; competitorBasis: { readonly skuGroupKey: 'B'; readonly competitorPrice: 120000; readonly competitorQty: 32; readonly competitorRatioBySize: { readonly '250': 0.6; }; }; competitorChannelId: 'cream'; competitorChannelLabel: 'Cream'; bufferStock: 0; selfWeightPct: 50; aiComment: { readonly prompt: 'prompt'; readonly answer: 'comment'; readonly generatedAt: '2026-04-23T00:00:00.000Z'; }; stockOrderResult: { readonly trendDailyMean: 10; readonly dailyMean: 10; readonly sigma: 1; readonly display: { readonly currentStockQtyTotal: 20; readonly totalOrderBalanceTotal: 4; readonly expectedInboundOrderBalanceTotal: 2; readonly sizeRows: readonly [{ readonly size: '250'; readonly currentStockQty: 20; readonly totalOrderBalance: 4; readonly expectedInboundOrderBalance: 2; }]; }; readonly safetyStockCalc: { readonly safetyStock: 12; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; readonly forecastQtyCalc: { readonly safetyStock: null; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; }; unitEconomics: { readonly unitPrice: 100000; readonly unitCost: 60000; readonly expectedFeeRatePct: 12; }; confirmedTotals: { readonly orderQty: 12; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; readonly expectedOpProfitRatePct: 28; }; sizeOrders: readonly [{ readonly size: '250'; readonly selfSharePct: 40; readonly competitorSharePct: 60; readonly blendedSharePct: 50; readonly forecastQty: 10; readonly recommendedQty: 12; readonly confirmQty: 12; }]; }; schemaVersion: 2; skuGroupKey: 'B'; savedAt: '2026-04-23T00:00:00.000Z'; } = {
      ...validSnapshot,
      extraMeta: { source: 'test' },
      context: {
        ...validSnapshot.context,
        unknownContextField: true,
      },
      drawer1: {
        ...validSnapshot.drawer1,
        unknownDrawer1Field: true,
        summary: {
          ...validSnapshot.drawer1.summary,
          unknownSummaryField: true,
        },
      },
      drawer2: {
        ...validSnapshot.drawer2,
        unknownDrawer2Field: true,
        stockOrderRequest: {
          ...validSnapshot.drawer2.stockOrderRequest,
          unknownStockOrderRequestField: true,
        },
      },
    }
    const parsed: OrderSnapshotDocumentV2 = parseOrderSnapshot(withExtra)
    expect(parsed).toEqual(validSnapshot)
    expect(parsed).not.toHaveProperty('extraMeta')
    expect(parsed.context).not.toHaveProperty('unknownContextField')
    expect(parsed.drawer1).not.toHaveProperty('unknownDrawer1Field')
    expect(parsed.drawer1.summary).not.toHaveProperty('unknownSummaryField')
    expect(parsed.drawer2).not.toHaveProperty('unknownDrawer2Field')
    expect(parsed.drawer2.stockOrderRequest).toEqual(validSnapshot.drawer2.stockOrderRequest)
    expect(parsed.drawer2.stockOrderRequest).not.toHaveProperty('unknownStockOrderRequestField')
  })

  it('throws when snapshot body is missing', () : void => {
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(null)).toThrow()
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(undefined)).toThrow()
  })

  it('throws when snapshot body is non-object primitive', () : void => {
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot('text')).toThrow()
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(123)).toThrow()
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(true)).toThrow()
  })

  it('throws when snapshot body is empty object', () : void => {
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot({})).toThrow()
  })

  it('throws when schemaVersion does not match current version', () : void => {
    const wrongVersion: { schemaVersion: number; skuGroupKey: 'B'; savedAt: '2026-04-23T00:00:00.000Z'; context: { readonly periodStart: '2026-01-01'; readonly periodEnd: '2026-01-31'; readonly forecastMonths: 8; readonly dailyTrendStartMonth: '2026-01'; readonly dailyTrendLeadTimeDays: 30; }; drawer1: { readonly summary: { readonly skuGroupKey: 'B'; readonly productName: 'Runner'; readonly brand: 'Brand'; readonly category: 'Shoes'; readonly code: 'RUN'; readonly colorCode: 'BLK'; readonly price: 100000; readonly qty: 80; readonly availableStock: 20; }; }; drawer2: { readonly competitorBasis: { readonly skuGroupKey: 'B'; readonly competitorPrice: 120000; readonly competitorQty: 32; readonly competitorRatioBySize: { readonly '250': 0.6; }; }; readonly competitorChannelId: 'cream'; readonly competitorChannelLabel: 'Cream'; readonly bufferStock: 0; readonly selfWeightPct: 50; readonly aiComment: { readonly prompt: 'prompt'; readonly answer: 'comment'; readonly generatedAt: '2026-04-23T00:00:00.000Z'; }; readonly stockOrderRequest: { readonly currentOrderInboundDueDate: '2026-02-01'; readonly nextOrderInboundDueDate: '2026-02-28'; readonly leadTimeDays: 30; readonly dailyMeanOverride: 10; }; readonly stockOrderResult: { readonly trendDailyMean: 10; readonly dailyMean: 10; readonly sigma: 1; readonly display: { readonly currentStockQtyTotal: 20; readonly totalOrderBalanceTotal: 4; readonly expectedInboundOrderBalanceTotal: 2; readonly sizeRows: readonly [{ readonly size: '250'; readonly currentStockQty: 20; readonly totalOrderBalance: 4; readonly expectedInboundOrderBalance: 2; }]; }; readonly safetyStockCalc: { readonly safetyStock: 12; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; readonly forecastQtyCalc: { readonly safetyStock: null; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; }; readonly unitEconomics: { readonly unitPrice: 100000; readonly unitCost: 60000; readonly expectedFeeRatePct: 12; }; readonly confirmedTotals: { readonly orderQty: 12; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; readonly expectedOpProfitRatePct: 28; }; readonly sizeOrders: readonly [{ readonly size: '250'; readonly selfSharePct: 40; readonly competitorSharePct: 60; readonly blendedSharePct: 50; readonly forecastQty: 10; readonly recommendedQty: 12; readonly confirmQty: 12; }]; }; } = { ...validSnapshot, schemaVersion: 1 }
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(wrongVersion)).toThrow()
  })

  it('throws when schemaVersion type is invalid', () : void => {
    const wrongTypeVersion: { schemaVersion: string; skuGroupKey: 'B'; savedAt: '2026-04-23T00:00:00.000Z'; context: { readonly periodStart: '2026-01-01'; readonly periodEnd: '2026-01-31'; readonly forecastMonths: 8; readonly dailyTrendStartMonth: '2026-01'; readonly dailyTrendLeadTimeDays: 30; }; drawer1: { readonly summary: { readonly skuGroupKey: 'B'; readonly productName: 'Runner'; readonly brand: 'Brand'; readonly category: 'Shoes'; readonly code: 'RUN'; readonly colorCode: 'BLK'; readonly price: 100000; readonly qty: 80; readonly availableStock: 20; }; }; drawer2: { readonly competitorBasis: { readonly skuGroupKey: 'B'; readonly competitorPrice: 120000; readonly competitorQty: 32; readonly competitorRatioBySize: { readonly '250': 0.6; }; }; readonly competitorChannelId: 'cream'; readonly competitorChannelLabel: 'Cream'; readonly bufferStock: 0; readonly selfWeightPct: 50; readonly aiComment: { readonly prompt: 'prompt'; readonly answer: 'comment'; readonly generatedAt: '2026-04-23T00:00:00.000Z'; }; readonly stockOrderRequest: { readonly currentOrderInboundDueDate: '2026-02-01'; readonly nextOrderInboundDueDate: '2026-02-28'; readonly leadTimeDays: 30; readonly dailyMeanOverride: 10; }; readonly stockOrderResult: { readonly trendDailyMean: 10; readonly dailyMean: 10; readonly sigma: 1; readonly display: { readonly currentStockQtyTotal: 20; readonly totalOrderBalanceTotal: 4; readonly expectedInboundOrderBalanceTotal: 2; readonly sizeRows: readonly [{ readonly size: '250'; readonly currentStockQty: 20; readonly totalOrderBalance: 4; readonly expectedInboundOrderBalance: 2; }]; }; readonly safetyStockCalc: { readonly safetyStock: 12; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; readonly forecastQtyCalc: { readonly safetyStock: null; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; }; readonly unitEconomics: { readonly unitPrice: 100000; readonly unitCost: 60000; readonly expectedFeeRatePct: 12; }; readonly confirmedTotals: { readonly orderQty: 12; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; readonly expectedOpProfitRatePct: 28; }; readonly sizeOrders: readonly [{ readonly size: '250'; readonly selfSharePct: 40; readonly competitorSharePct: 60; readonly blendedSharePct: 50; readonly forecastQty: 10; readonly recommendedQty: 12; readonly confirmQty: 12; }]; }; } = { ...validSnapshot, schemaVersion: '2' }
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(wrongTypeVersion)).toThrow()
  })

  it('throws when drawer block is missing', () : void => {
    const withoutDrawer1: { drawer1: null; schemaVersion: 2; skuGroupKey: 'B'; savedAt: '2026-04-23T00:00:00.000Z'; context: { readonly periodStart: '2026-01-01'; readonly periodEnd: '2026-01-31'; readonly forecastMonths: 8; readonly dailyTrendStartMonth: '2026-01'; readonly dailyTrendLeadTimeDays: 30; }; drawer2: { readonly competitorBasis: { readonly skuGroupKey: 'B'; readonly competitorPrice: 120000; readonly competitorQty: 32; readonly competitorRatioBySize: { readonly '250': 0.6; }; }; readonly competitorChannelId: 'cream'; readonly competitorChannelLabel: 'Cream'; readonly bufferStock: 0; readonly selfWeightPct: 50; readonly aiComment: { readonly prompt: 'prompt'; readonly answer: 'comment'; readonly generatedAt: '2026-04-23T00:00:00.000Z'; }; readonly stockOrderRequest: { readonly currentOrderInboundDueDate: '2026-02-01'; readonly nextOrderInboundDueDate: '2026-02-28'; readonly leadTimeDays: 30; readonly dailyMeanOverride: 10; }; readonly stockOrderResult: { readonly trendDailyMean: 10; readonly dailyMean: 10; readonly sigma: 1; readonly display: { readonly currentStockQtyTotal: 20; readonly totalOrderBalanceTotal: 4; readonly expectedInboundOrderBalanceTotal: 2; readonly sizeRows: readonly [{ readonly size: '250'; readonly currentStockQty: 20; readonly totalOrderBalance: 4; readonly expectedInboundOrderBalance: 2; }]; }; readonly safetyStockCalc: { readonly safetyStock: 12; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; readonly forecastQtyCalc: { readonly safetyStock: null; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; }; readonly unitEconomics: { readonly unitPrice: 100000; readonly unitCost: 60000; readonly expectedFeeRatePct: 12; }; readonly confirmedTotals: { readonly orderQty: 12; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; readonly expectedOpProfitRatePct: 28; }; readonly sizeOrders: readonly [{ readonly size: '250'; readonly selfSharePct: 40; readonly competitorSharePct: 60; readonly blendedSharePct: 50; readonly forecastQty: 10; readonly recommendedQty: 12; readonly confirmQty: 12; }]; }; } = { ...validSnapshot, drawer1: null }
    const withoutDrawer2: { drawer2: null; schemaVersion: 2; skuGroupKey: 'B'; savedAt: '2026-04-23T00:00:00.000Z'; context: { readonly periodStart: '2026-01-01'; readonly periodEnd: '2026-01-31'; readonly forecastMonths: 8; readonly dailyTrendStartMonth: '2026-01'; readonly dailyTrendLeadTimeDays: 30; }; drawer1: { readonly summary: { readonly skuGroupKey: 'B'; readonly productName: 'Runner'; readonly brand: 'Brand'; readonly category: 'Shoes'; readonly code: 'RUN'; readonly colorCode: 'BLK'; readonly price: 100000; readonly qty: 80; readonly availableStock: 20; }; }; } = { ...validSnapshot, drawer2: null }
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(withoutDrawer1)).toThrow(/drawer/)
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(withoutDrawer2)).toThrow(/drawer/)
  })

  it('throws when drawer block is undefined', () : void => {
    const withoutDrawer1: { drawer1: undefined; schemaVersion: 2; skuGroupKey: 'B'; savedAt: '2026-04-23T00:00:00.000Z'; context: { readonly periodStart: '2026-01-01'; readonly periodEnd: '2026-01-31'; readonly forecastMonths: 8; readonly dailyTrendStartMonth: '2026-01'; readonly dailyTrendLeadTimeDays: 30; }; drawer2: { readonly competitorBasis: { readonly skuGroupKey: 'B'; readonly competitorPrice: 120000; readonly competitorQty: 32; readonly competitorRatioBySize: { readonly '250': 0.6; }; }; readonly competitorChannelId: 'cream'; readonly competitorChannelLabel: 'Cream'; readonly bufferStock: 0; readonly selfWeightPct: 50; readonly aiComment: { readonly prompt: 'prompt'; readonly answer: 'comment'; readonly generatedAt: '2026-04-23T00:00:00.000Z'; }; readonly stockOrderRequest: { readonly currentOrderInboundDueDate: '2026-02-01'; readonly nextOrderInboundDueDate: '2026-02-28'; readonly leadTimeDays: 30; readonly dailyMeanOverride: 10; }; readonly stockOrderResult: { readonly trendDailyMean: 10; readonly dailyMean: 10; readonly sigma: 1; readonly display: { readonly currentStockQtyTotal: 20; readonly totalOrderBalanceTotal: 4; readonly expectedInboundOrderBalanceTotal: 2; readonly sizeRows: readonly [{ readonly size: '250'; readonly currentStockQty: 20; readonly totalOrderBalance: 4; readonly expectedInboundOrderBalance: 2; }]; }; readonly safetyStockCalc: { readonly safetyStock: 12; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; readonly forecastQtyCalc: { readonly safetyStock: null; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; }; readonly unitEconomics: { readonly unitPrice: 100000; readonly unitCost: 60000; readonly expectedFeeRatePct: 12; }; readonly confirmedTotals: { readonly orderQty: 12; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; readonly expectedOpProfitRatePct: 28; }; readonly sizeOrders: readonly [{ readonly size: '250'; readonly selfSharePct: 40; readonly competitorSharePct: 60; readonly blendedSharePct: 50; readonly forecastQty: 10; readonly recommendedQty: 12; readonly confirmQty: 12; }]; }; } = { ...validSnapshot, drawer1: undefined }
    const withoutDrawer2: { drawer2: undefined; schemaVersion: 2; skuGroupKey: 'B'; savedAt: '2026-04-23T00:00:00.000Z'; context: { readonly periodStart: '2026-01-01'; readonly periodEnd: '2026-01-31'; readonly forecastMonths: 8; readonly dailyTrendStartMonth: '2026-01'; readonly dailyTrendLeadTimeDays: 30; }; drawer1: { readonly summary: { readonly skuGroupKey: 'B'; readonly productName: 'Runner'; readonly brand: 'Brand'; readonly category: 'Shoes'; readonly code: 'RUN'; readonly colorCode: 'BLK'; readonly price: 100000; readonly qty: 80; readonly availableStock: 20; }; }; } = { ...validSnapshot, drawer2: undefined }
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(withoutDrawer1)).toThrow(/drawer/)
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(withoutDrawer2)).toThrow(/drawer/)
  })

  it('throws when skuGroupKey is missing or empty', () : void => {
    const missingSkuGroupKey: { skuGroupKey: null; schemaVersion: 2; savedAt: '2026-04-23T00:00:00.000Z'; context: { readonly periodStart: '2026-01-01'; readonly periodEnd: '2026-01-31'; readonly forecastMonths: 8; readonly dailyTrendStartMonth: '2026-01'; readonly dailyTrendLeadTimeDays: 30; }; drawer1: { readonly summary: { readonly skuGroupKey: 'B'; readonly productName: 'Runner'; readonly brand: 'Brand'; readonly category: 'Shoes'; readonly code: 'RUN'; readonly colorCode: 'BLK'; readonly price: 100000; readonly qty: 80; readonly availableStock: 20; }; }; drawer2: { readonly competitorBasis: { readonly skuGroupKey: 'B'; readonly competitorPrice: 120000; readonly competitorQty: 32; readonly competitorRatioBySize: { readonly '250': 0.6; }; }; readonly competitorChannelId: 'cream'; readonly competitorChannelLabel: 'Cream'; readonly bufferStock: 0; readonly selfWeightPct: 50; readonly aiComment: { readonly prompt: 'prompt'; readonly answer: 'comment'; readonly generatedAt: '2026-04-23T00:00:00.000Z'; }; readonly stockOrderRequest: { readonly currentOrderInboundDueDate: '2026-02-01'; readonly nextOrderInboundDueDate: '2026-02-28'; readonly leadTimeDays: 30; readonly dailyMeanOverride: 10; }; readonly stockOrderResult: { readonly trendDailyMean: 10; readonly dailyMean: 10; readonly sigma: 1; readonly display: { readonly currentStockQtyTotal: 20; readonly totalOrderBalanceTotal: 4; readonly expectedInboundOrderBalanceTotal: 2; readonly sizeRows: readonly [{ readonly size: '250'; readonly currentStockQty: 20; readonly totalOrderBalance: 4; readonly expectedInboundOrderBalance: 2; }]; }; readonly safetyStockCalc: { readonly safetyStock: 12; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; readonly forecastQtyCalc: { readonly safetyStock: null; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; }; readonly unitEconomics: { readonly unitPrice: 100000; readonly unitCost: 60000; readonly expectedFeeRatePct: 12; }; readonly confirmedTotals: { readonly orderQty: 12; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; readonly expectedOpProfitRatePct: 28; }; readonly sizeOrders: readonly [{ readonly size: '250'; readonly selfSharePct: 40; readonly competitorSharePct: 60; readonly blendedSharePct: 50; readonly forecastQty: 10; readonly recommendedQty: 12; readonly confirmQty: 12; }]; }; } = { ...validSnapshot, skuGroupKey: null }
    const emptySkuGroupKey: { skuGroupKey: string; schemaVersion: 2; savedAt: '2026-04-23T00:00:00.000Z'; context: { readonly periodStart: '2026-01-01'; readonly periodEnd: '2026-01-31'; readonly forecastMonths: 8; readonly dailyTrendStartMonth: '2026-01'; readonly dailyTrendLeadTimeDays: 30; }; drawer1: { readonly summary: { readonly skuGroupKey: 'B'; readonly productName: 'Runner'; readonly brand: 'Brand'; readonly category: 'Shoes'; readonly code: 'RUN'; readonly colorCode: 'BLK'; readonly price: 100000; readonly qty: 80; readonly availableStock: 20; }; }; drawer2: { readonly competitorBasis: { readonly skuGroupKey: 'B'; readonly competitorPrice: 120000; readonly competitorQty: 32; readonly competitorRatioBySize: { readonly '250': 0.6; }; }; readonly competitorChannelId: 'cream'; readonly competitorChannelLabel: 'Cream'; readonly bufferStock: 0; readonly selfWeightPct: 50; readonly aiComment: { readonly prompt: 'prompt'; readonly answer: 'comment'; readonly generatedAt: '2026-04-23T00:00:00.000Z'; }; readonly stockOrderRequest: { readonly currentOrderInboundDueDate: '2026-02-01'; readonly nextOrderInboundDueDate: '2026-02-28'; readonly leadTimeDays: 30; readonly dailyMeanOverride: 10; }; readonly stockOrderResult: { readonly trendDailyMean: 10; readonly dailyMean: 10; readonly sigma: 1; readonly display: { readonly currentStockQtyTotal: 20; readonly totalOrderBalanceTotal: 4; readonly expectedInboundOrderBalanceTotal: 2; readonly sizeRows: readonly [{ readonly size: '250'; readonly currentStockQty: 20; readonly totalOrderBalance: 4; readonly expectedInboundOrderBalance: 2; }]; }; readonly safetyStockCalc: { readonly safetyStock: 12; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; readonly forecastQtyCalc: { readonly safetyStock: null; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; }; readonly unitEconomics: { readonly unitPrice: 100000; readonly unitCost: 60000; readonly expectedFeeRatePct: 12; }; readonly confirmedTotals: { readonly orderQty: 12; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; readonly expectedOpProfitRatePct: 28; }; readonly sizeOrders: readonly [{ readonly size: '250'; readonly selfSharePct: 40; readonly competitorSharePct: 60; readonly blendedSharePct: 50; readonly forecastQty: 10; readonly recommendedQty: 12; readonly confirmQty: 12; }]; }; } = { ...validSnapshot, skuGroupKey: '' }
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(missingSkuGroupKey)).toThrow(/skuGroupKey/)
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(emptySkuGroupKey)).toThrow(/skuGroupKey/)
  })

  it('throws when skuGroupKey is not a string', () : void => {
    const numericSkuGroupKey: { skuGroupKey: number; schemaVersion: 2; savedAt: '2026-04-23T00:00:00.000Z'; context: { readonly periodStart: '2026-01-01'; readonly periodEnd: '2026-01-31'; readonly forecastMonths: 8; readonly dailyTrendStartMonth: '2026-01'; readonly dailyTrendLeadTimeDays: 30; }; drawer1: { readonly summary: { readonly skuGroupKey: 'B'; readonly productName: 'Runner'; readonly brand: 'Brand'; readonly category: 'Shoes'; readonly code: 'RUN'; readonly colorCode: 'BLK'; readonly price: 100000; readonly qty: 80; readonly availableStock: 20; }; }; drawer2: { readonly competitorBasis: { readonly skuGroupKey: 'B'; readonly competitorPrice: 120000; readonly competitorQty: 32; readonly competitorRatioBySize: { readonly '250': 0.6; }; }; readonly competitorChannelId: 'cream'; readonly competitorChannelLabel: 'Cream'; readonly bufferStock: 0; readonly selfWeightPct: 50; readonly aiComment: { readonly prompt: 'prompt'; readonly answer: 'comment'; readonly generatedAt: '2026-04-23T00:00:00.000Z'; }; readonly stockOrderRequest: { readonly currentOrderInboundDueDate: '2026-02-01'; readonly nextOrderInboundDueDate: '2026-02-28'; readonly leadTimeDays: 30; readonly dailyMeanOverride: 10; }; readonly stockOrderResult: { readonly trendDailyMean: 10; readonly dailyMean: 10; readonly sigma: 1; readonly display: { readonly currentStockQtyTotal: 20; readonly totalOrderBalanceTotal: 4; readonly expectedInboundOrderBalanceTotal: 2; readonly sizeRows: readonly [{ readonly size: '250'; readonly currentStockQty: 20; readonly totalOrderBalance: 4; readonly expectedInboundOrderBalance: 2; }]; }; readonly safetyStockCalc: { readonly safetyStock: 12; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; readonly forecastQtyCalc: { readonly safetyStock: null; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; }; readonly unitEconomics: { readonly unitPrice: 100000; readonly unitCost: 60000; readonly expectedFeeRatePct: 12; }; readonly confirmedTotals: { readonly orderQty: 12; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; readonly expectedOpProfitRatePct: 28; }; readonly sizeOrders: readonly [{ readonly size: '250'; readonly selfSharePct: 40; readonly competitorSharePct: 60; readonly blendedSharePct: 50; readonly forecastQty: 10; readonly recommendedQty: 12; readonly confirmQty: 12; }]; }; } = { ...validSnapshot, skuGroupKey: 1234 }
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(numericSkuGroupKey)).toThrow(/skuGroupKey/)
  })

  it('throws when top-level companyUuid is empty or not a string', () : void => {
    const emptyCompanyUuid: { companyUuid: string; schemaVersion: 2; skuGroupKey: 'B'; savedAt: '2026-04-23T00:00:00.000Z'; context: { readonly periodStart: '2026-01-01'; readonly periodEnd: '2026-01-31'; readonly forecastMonths: 8; readonly dailyTrendStartMonth: '2026-01'; readonly dailyTrendLeadTimeDays: 30; }; drawer1: { readonly summary: { readonly skuGroupKey: 'B'; readonly productName: 'Runner'; readonly brand: 'Brand'; readonly category: 'Shoes'; readonly code: 'RUN'; readonly colorCode: 'BLK'; readonly price: 100000; readonly qty: 80; readonly availableStock: 20; }; }; drawer2: { readonly competitorBasis: { readonly skuGroupKey: 'B'; readonly competitorPrice: 120000; readonly competitorQty: 32; readonly competitorRatioBySize: { readonly '250': 0.6; }; }; readonly competitorChannelId: 'cream'; readonly competitorChannelLabel: 'Cream'; readonly bufferStock: 0; readonly selfWeightPct: 50; readonly aiComment: { readonly prompt: 'prompt'; readonly answer: 'comment'; readonly generatedAt: '2026-04-23T00:00:00.000Z'; }; readonly stockOrderRequest: { readonly currentOrderInboundDueDate: '2026-02-01'; readonly nextOrderInboundDueDate: '2026-02-28'; readonly leadTimeDays: 30; readonly dailyMeanOverride: 10; }; readonly stockOrderResult: { readonly trendDailyMean: 10; readonly dailyMean: 10; readonly sigma: 1; readonly display: { readonly currentStockQtyTotal: 20; readonly totalOrderBalanceTotal: 4; readonly expectedInboundOrderBalanceTotal: 2; readonly sizeRows: readonly [{ readonly size: '250'; readonly currentStockQty: 20; readonly totalOrderBalance: 4; readonly expectedInboundOrderBalance: 2; }]; }; readonly safetyStockCalc: { readonly safetyStock: 12; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; readonly forecastQtyCalc: { readonly safetyStock: null; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; }; readonly unitEconomics: { readonly unitPrice: 100000; readonly unitCost: 60000; readonly expectedFeeRatePct: 12; }; readonly confirmedTotals: { readonly orderQty: 12; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; readonly expectedOpProfitRatePct: 28; }; readonly sizeOrders: readonly [{ readonly size: '250'; readonly selfSharePct: 40; readonly competitorSharePct: 60; readonly blendedSharePct: 50; readonly forecastQty: 10; readonly recommendedQty: 12; readonly confirmQty: 12; }]; }; } = { ...validSnapshot, companyUuid: '' }
    const nullCompanyUuid: { companyUuid: null; schemaVersion: 2; skuGroupKey: 'B'; savedAt: '2026-04-23T00:00:00.000Z'; context: { readonly periodStart: '2026-01-01'; readonly periodEnd: '2026-01-31'; readonly forecastMonths: 8; readonly dailyTrendStartMonth: '2026-01'; readonly dailyTrendLeadTimeDays: 30; }; drawer1: { readonly summary: { readonly skuGroupKey: 'B'; readonly productName: 'Runner'; readonly brand: 'Brand'; readonly category: 'Shoes'; readonly code: 'RUN'; readonly colorCode: 'BLK'; readonly price: 100000; readonly qty: 80; readonly availableStock: 20; }; }; drawer2: { readonly competitorBasis: { readonly skuGroupKey: 'B'; readonly competitorPrice: 120000; readonly competitorQty: 32; readonly competitorRatioBySize: { readonly '250': 0.6; }; }; readonly competitorChannelId: 'cream'; readonly competitorChannelLabel: 'Cream'; readonly bufferStock: 0; readonly selfWeightPct: 50; readonly aiComment: { readonly prompt: 'prompt'; readonly answer: 'comment'; readonly generatedAt: '2026-04-23T00:00:00.000Z'; }; readonly stockOrderRequest: { readonly currentOrderInboundDueDate: '2026-02-01'; readonly nextOrderInboundDueDate: '2026-02-28'; readonly leadTimeDays: 30; readonly dailyMeanOverride: 10; }; readonly stockOrderResult: { readonly trendDailyMean: 10; readonly dailyMean: 10; readonly sigma: 1; readonly display: { readonly currentStockQtyTotal: 20; readonly totalOrderBalanceTotal: 4; readonly expectedInboundOrderBalanceTotal: 2; readonly sizeRows: readonly [{ readonly size: '250'; readonly currentStockQty: 20; readonly totalOrderBalance: 4; readonly expectedInboundOrderBalance: 2; }]; }; readonly safetyStockCalc: { readonly safetyStock: 12; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; readonly forecastQtyCalc: { readonly safetyStock: null; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; }; readonly unitEconomics: { readonly unitPrice: 100000; readonly unitCost: 60000; readonly expectedFeeRatePct: 12; }; readonly confirmedTotals: { readonly orderQty: 12; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; readonly expectedOpProfitRatePct: 28; }; readonly sizeOrders: readonly [{ readonly size: '250'; readonly selfSharePct: 40; readonly competitorSharePct: 60; readonly blendedSharePct: 50; readonly forecastQty: 10; readonly recommendedQty: 12; readonly confirmQty: 12; }]; }; } = { ...validSnapshot, companyUuid: null }
    const numericCompanyUuid: { companyUuid: number; schemaVersion: 2; skuGroupKey: 'B'; savedAt: '2026-04-23T00:00:00.000Z'; context: { readonly periodStart: '2026-01-01'; readonly periodEnd: '2026-01-31'; readonly forecastMonths: 8; readonly dailyTrendStartMonth: '2026-01'; readonly dailyTrendLeadTimeDays: 30; }; drawer1: { readonly summary: { readonly skuGroupKey: 'B'; readonly productName: 'Runner'; readonly brand: 'Brand'; readonly category: 'Shoes'; readonly code: 'RUN'; readonly colorCode: 'BLK'; readonly price: 100000; readonly qty: 80; readonly availableStock: 20; }; }; drawer2: { readonly competitorBasis: { readonly skuGroupKey: 'B'; readonly competitorPrice: 120000; readonly competitorQty: 32; readonly competitorRatioBySize: { readonly '250': 0.6; }; }; readonly competitorChannelId: 'cream'; readonly competitorChannelLabel: 'Cream'; readonly bufferStock: 0; readonly selfWeightPct: 50; readonly aiComment: { readonly prompt: 'prompt'; readonly answer: 'comment'; readonly generatedAt: '2026-04-23T00:00:00.000Z'; }; readonly stockOrderRequest: { readonly currentOrderInboundDueDate: '2026-02-01'; readonly nextOrderInboundDueDate: '2026-02-28'; readonly leadTimeDays: 30; readonly dailyMeanOverride: 10; }; readonly stockOrderResult: { readonly trendDailyMean: 10; readonly dailyMean: 10; readonly sigma: 1; readonly display: { readonly currentStockQtyTotal: 20; readonly totalOrderBalanceTotal: 4; readonly expectedInboundOrderBalanceTotal: 2; readonly sizeRows: readonly [{ readonly size: '250'; readonly currentStockQty: 20; readonly totalOrderBalance: 4; readonly expectedInboundOrderBalance: 2; }]; }; readonly safetyStockCalc: { readonly safetyStock: 12; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; readonly forecastQtyCalc: { readonly safetyStock: null; readonly recommendedOrderQty: 12; readonly expectedOrderAmount: 720000; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; }; }; readonly unitEconomics: { readonly unitPrice: 100000; readonly unitCost: 60000; readonly expectedFeeRatePct: 12; }; readonly confirmedTotals: { readonly orderQty: 12; readonly expectedSalesAmount: 1200000; readonly expectedOpProfit: 336000; readonly expectedOpProfitRatePct: 28; }; readonly sizeOrders: readonly [{ readonly size: '250'; readonly selfSharePct: 40; readonly competitorSharePct: 60; readonly blendedSharePct: 50; readonly forecastQty: 10; readonly recommendedQty: 12; readonly confirmQty: 12; }]; }; } = { ...validSnapshot, companyUuid: 1234 }

    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(emptyCompanyUuid)).toThrow(/companyUuid/)
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(nullCompanyUuid)).toThrow(/companyUuid/)
    expect(() : OrderSnapshotDocumentV2 => parseOrderSnapshot(numericCompanyUuid)).toThrow(/companyUuid/)
  })
})
