import { adminGoogleSheetRequests, adminGptKeyRequests, authRequests, dashboardRequests } from './requests'

export const getCurrentAuthSession = authRequests.getCurrentSession
export const login = authRequests.login
export const updateCurrentUser = authRequests.updateCurrentUser
export const changeCurrentUserPassword = authRequests.changeCurrentUserPassword
export const getAdminUsers = authRequests.getAdminUsers
export const createAdminUser = authRequests.createAdminUser
export const updateAdminUser = authRequests.updateAdminUser
export const resetAdminUserPassword = authRequests.resetAdminUserPassword
export const deleteAdminUser = authRequests.deleteAdminUser
export const logout = authRequests.logout

export const getAdminGptKeys = adminGptKeyRequests.getAdminGptKeys
export const createAdminGptKey = adminGptKeyRequests.createAdminGptKey
export const updateAdminGptKey = adminGptKeyRequests.updateAdminGptKey
export const rotateAdminGptKey = adminGptKeyRequests.rotateAdminGptKey
export const testAdminGptKey = adminGptKeyRequests.testAdminGptKey
export const deleteAdminGptKey = adminGptKeyRequests.deleteAdminGptKey

export const getAdminGoogleSheetConfigs = adminGoogleSheetRequests.getAdminGoogleSheetConfigs
export const createAdminGoogleSheetConfig = adminGoogleSheetRequests.createAdminGoogleSheetConfig
export const updateAdminGoogleSheetConfig = adminGoogleSheetRequests.updateAdminGoogleSheetConfig
export const deleteAdminGoogleSheetConfig = adminGoogleSheetRequests.deleteAdminGoogleSheetConfig

export const getSelfSales = dashboardRequests.getSelfSales
export const getCompetitorSales = dashboardRequests.getCompetitorSales
export const getSelfSalesScatterGrid = dashboardRequests.getSelfSalesScatterGrid
export const getCompetitorSalesScatterGrid = dashboardRequests.getCompetitorSalesScatterGrid
export const getSalesFilterMeta = dashboardRequests.getSalesFilterMeta
export const getProductDrawerBundle = dashboardRequests.getProductDrawerBundle
export const getSecondaryCompetitorChannels = dashboardRequests.getSecondaryCompetitorChannels
export const getSecondaryAiComment = dashboardRequests.getSecondaryAiComment
export const getCandidateStashes = dashboardRequests.getCandidateStashes
export const getCandidateItemsByStash = dashboardRequests.getCandidateItemsByStash
export const subscribeCandidateOrderMetrics = dashboardRequests.subscribeCandidateOrderMetrics
export const startCandidateStashAnalysis = dashboardRequests.startCandidateStashAnalysis
export const subscribeCandidateStashAnalysis = dashboardRequests.subscribeCandidateStashAnalysis
export const getCandidateRecommendations = dashboardRequests.getCandidateRecommendations
export const getCandidateItemByUuid = dashboardRequests.getCandidateItemByUuid
export const deleteCandidateItem = dashboardRequests.deleteCandidateItem
export const deleteCandidateItems = dashboardRequests.deleteCandidateItems
export const deleteCandidateStash = dashboardRequests.deleteCandidateStash
export const createCandidateStash = dashboardRequests.createCandidateStash
export const duplicateCandidateStash = dashboardRequests.duplicateCandidateStash
export const updateCandidateStash = dashboardRequests.updateCandidateStash
export const appendCandidateItems = dashboardRequests.appendCandidateItems
export const updateCandidateItem = dashboardRequests.updateCandidateItem
export const getCandidateStashExcelTemplateDownload = dashboardRequests.getCandidateStashExcelTemplateDownload
export const uploadCandidateStashExcel = dashboardRequests.uploadCandidateStashExcel

export const dashboardApi = dashboardRequests
